package com.creative.hfs.hfsbackend.model.enums;

import lombok.Getter;

@Getter
public enum Department {
    DIGITAL_PRODUCT_ENGINEERING_CAE(1),
    INTELLIGENT_CONNECTED_PRODUCTS(2),
    DIGITAL_PLANT_AND_PROCESS_ENGINEERING(3),
    DIGITAL_PRODUCT_ENGINEERING_HI(4),
    DIGITAL_PRODUCT_ENGINEERING_ACE(5),
    DIGITAL_DISCRETE_MANUFACTURING_ENGINEERING(6),
    IN_CLIENT_SERVICES(7),
    CORPORATE(8),
    QUALITY_ASSURANCE_AND_BUSINESS_EXCELLENCE(9),
    TALENT_ACQUISITION(10),
    FINANCE_AND_ACCOUNTS(11),
    INFRASTRUCTURE_MANAGEMENT_GROUP_ADMIN(12),
    DIGITAL_TECHNOLOGIES(13),
    WORK_FORCE_ENABLEMENT(14),
    HUMAN_RESOURCES(15),
    MARKET_RESEARCH_AND_SALES_ENABLEMENT(16),
    MARKETING(17),
    BUSINESS_DEVELOPMENT(18);

    private final int id;

    Department(int id) {
        this.id = id;
    }

}

